update

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,9 +1,22 @@
 #!/usr/bin/env bash
-if ! grep -q "syncr" ~/.bashrc
-then
-    echo "alias syncr='python3 $(pwd)/run.py'" >> ~/.bashrc
-    echo "> Syncr: alias for Syncr has been added to bashrc"
-    source ~/.bashrc
-else
-    echo "> Syncr: alias already exists in bashrc"
-fi
+case $(uname | tr '[:upper:]' '[:lower:]') in
+  linux*)
+        if ! grep -q "syncr" ~/.bashrc
+        then
+            echo "alias syncr='python3 $(pwd)/run.py'" >> ~/.bashrc
+            echo "> Syncr: alias for Syncr has been added to bashrc"
+            source ~/.bashrc
+        else
+            echo "> Syncr: alias already exists in bashrc"
+        fi
+    ;;
+  darwin*)
+    echo "> Syncr: Mac setup not supported yet."
+    ;;
+  msys*)
+    echo "> Syncr: Windows setup not supported yet."
+    ;;
+  *)
+    echo "> Syncr: Cannot detect OS type."
+    ;;
+esac
